import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { Quando } from "next/font/google";
import "./globals.css";
import Info from "@/components/Info"
import Header from "@/components/Header"
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const quando = Quando({
  variable: "--font-quando",
  weight: ["400"], 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${quando.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Info />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
