// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  expertise: dynamic(() => import("./Expertise")),
  hero: dynamic(() => import("./Hero")),
};
